### ISSUE TITLE
Move to the colony org

### ISSUE THREAD

**Issue by chmanie** [sprusr/colony-gql#1]
Hey Scott!

Do you think we could move this to the colony org for further development?

Cheers!

**Comment by sprusr** [comment]
Sure! More than happy to, but I "don't have permission to create public repos on JoinColony".

**Comment by chmanie** [comment]
Huh! Can you make me admin of this then? That'd work I reckon!

**Comment by sprusr** [comment]
@chmanie I did a transfer request to you last week

**Comment by chmanie** [comment]
Huh. I didn’t get any (I think?).
Can you do that again?

**Comment by sprusr** [comment]
Just cancelled and did it again:
![image](https://user-images.githubusercontent.com/7497084/74221441-cfabeb00-4cba-11ea-910f-3efb1ce813bf.png)

**Comment by chmanie** [comment]
We will never get this done :(

**Comment by chmanie** [comment]
Can you try again? I'm not getting any notifications whatsoever

**Comment by sprusr** [comment]
@chmanie I just initiated the transfer again

**Comment by chmanie** [comment]
Turns out I can't receive ANY emails from github. Let me sort this out and then we can try again (one last time, hopefully)

**Comment by chmanie** [comment]
Okay, Scott, please try to do it once more! I can get emails again :) Sorry for this whole mess

**Comment by sprusr** [comment]
Haha no worries, fingers crossed for this time! 🤞 Have done the transfer request

**Comment by sprusr** [comment]
It's done!
